# Generated by Django 5.0.6 on 2024-08-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0002_rename_url_productos_product_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnew', models.IntegerField()),
                ('idold', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='productos',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='product_img',
        ),
        migrations.AddField(
            model_name='productos',
            name='idn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='idol',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
