# Generated by Django 5.0.6 on 2024-08-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0003_productid_remove_productos_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
