# Generated by Django 4.1.13 on 2024-08-30 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0004_delete_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductId',
        ),
    ]
