# Generated by Django 4.1.13 on 2024-08-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraperApp', '0005_delete_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnew', models.IntegerField()),
                ('idold', models.IntegerField()),
            ],
        ),
    ]
