# Generated by Django 4.1.13 on 2024-08-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='idp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
