# Generated by Django 4.1.13 on 2024-08-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0007_documento_idp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='idp',
            field=models.IntegerField(default=0),
        ),
    ]
